# ============================================================================
# Copyright 2025 Richard Spencer Landry Jr, Ph.D.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

# Compiler and flags
CC      = gcc
CFLAGS  = -O2 -I$(HOME)/sundials-install/include
LDFLAGS = -L$(HOME)/sundials-install/lib -lsundials_cvode -lsundials_nvecserial -lm

# Files
TARGET  = cvSimple
SRC     = cvSimple.c

# Build rules
all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC) $(LDFLAGS)

clean:
	rm -f $(TARGET) *.o
